#pragma kernel CopyRaw

Texture2DArray<float> _EnvironmentDepthTexture;
float _EnvironmentDepthTextureSize;
RWStructuredBuffer<float> _RawDepthProbe;

[numthreads(32, 32, 1)]
void CopyRaw(uint3 id : SV_DispatchThreadID)
{
    static const uint textureSize = 128;
    static const uint numThreads = 32;
    static const uint iterationsPerThread = textureSize / numThreads;
    const float downscale = _EnvironmentDepthTextureSize / textureSize;

    const uint x = id.x * iterationsPerThread;
    const uint y = id.y * iterationsPerThread;
    for (uint i = 0; i < iterationsPerThread; i++)
    {
        for (uint j = 0; j < iterationsPerThread; j++)
        {
            [unroll]
            for (uint eyeIndex = 0; eyeIndex < 2; eyeIndex++)
            {
                const uint dstX = x + i;
                const uint dstY = y + j;
                const uint sourceX = min((uint)(dstX * downscale), (uint)_EnvironmentDepthTextureSize - 1);
                const uint sourceY = min((uint)(dstY * downscale), (uint)_EnvironmentDepthTextureSize - 1);
                const uint targetIndex = dstX + dstY * textureSize + textureSize * textureSize * eyeIndex;
                _RawDepthProbe[targetIndex] = _EnvironmentDepthTexture.Load(int4(sourceX, sourceY, eyeIndex, 0));
            }
        }
    }
}
